### ISSUE TITLE
bd() call

### ISSUE THREAD

**Issue by adrianbj** [gebeer/FieldtypeImageFromPage#1]
https://github.com/gebeer/FieldtypeImageFromPage/blob/ee9b31d461c94ed9a3907e1a8e89dab3783bdcb8/FieldtypeImageFromPage.module#L408

**Comment by gebeer** [comment]
resolved https://github.com/gebeer/FieldtypeImageFromPage/commit/e413bfb4bc785e4e710d6c11718c172fca7cfb19
